### ISSUE TITLE
Use actix-web 4

### ISSUE THREAD

**Issue by ctron** [cloudevents/sdk-rust#114]
Although actix-web 4 is only released as beta yet, it is required for the switch to tokio 1.

**Comment by slinkydeveloper** [comment]
I see it's still in beta https://github.com/actix/actix-web/releases/tag/web-v4.0.0-beta.1, I would love to wait for the final release before updating it here. How does it sounds?

**Comment by andrewwebber** [comment]
Also observing this, would be great to have a branch somewhere to test. For example using OpenTelemetry in Rust requires Tokio1 and I love to comform OpenTel + ActixWeb + Cloudevents = :heart:

**Comment by andrewwebber** [comment]
@ctron Thank you for putting together your fork
