### ISSUE TITLE
Possible Serialization bug?

### ISSUE THREAD

**Issue by No9** [cloudevents/sdk-rust#125]
Hi All
Testing the tide websocket implementation using the example message from 
https://github.com/cloudevents/spec/blob/master/json-format.md#32-examples 
```
{
    "specversion" : "1.0",
    "type" : "com.example.someevent",
    "source" : "/mycontext",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleothervalue" : 5,
    "unsetextension": null,
    "datacontenttype" : "text/xml",
    "data" : "<much wow=\"xml\"/>"
}
```
Specifically this line https://github.com/cloudevents/sdk-rust/pull/117/commits/205e16ad009cae33ba03a76398b47251cb6b3713#diff-97633925b0ac8233888bd3bdc2313999cd86c04f1e7e56a62a8cb1e8d58ba5eaR50 
```
let v: Event = serde_json::from_str(&message).unwrap(); 
```
fails with 
```
thread 'async-std/runtime' panicked at 'called `Result::unwrap()` on an 
`Err` value: Error("data did not match any variant of untagged enum ExtensionValue", 
line: 0, column: 0)', src/main.rs:50:71
```
If I remove the property set to **null** `"unsetextension": null,` the message works as expected.
```
{
    "specversion" : "1.0",
    "type" : "com.example.someevent",
    "source" : "/mycontext",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleothervalue" : 5,
    "datacontenttype" : "text/xml",
    "data" : "<much wow=\"xml\"/>"
}
```
According to the docs `null` should be treated as unset or omitted 
https://github.com/cloudevents/spec/blob/70823088e52b393b4251abd1ab03b6cfa233d427/json-format.md#22-type-system-mapping. 

Do you have any preferences for which it should be?

**Comment by slinkydeveloper** [comment]
Yeah I guess that's an issue we need to solve, do you want to tackle it?

**Comment by No9** [comment]
I can take a look but is there a preference between omitting vs unset?
My understanding of omitting is **discard the property totally** where as unset would mean setting the value to None.

**Comment by slinkydeveloper** [comment]
yes, me too: when null, it's like none
