### ISSUE TITLE
Attributes iterator

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-rust#15]
Event should expose a function that allows to iterate over available attributes

**Comment by pranav-bhatt** [comment]
Hi! I'm interested in working on this issue, is this still open? I'm kinda new to Rust and CE, but I'll grasp quickly.

**Comment by slinkydeveloper** [comment]
@pranav-bhatt I have a WIP here: https://github.com/cloudevents/sdk-rust/tree/iter_experiments I think you can start from this one :)
