### ISSUE TITLE
Fails to parse event which has non-JSON data section with JSON content type

### ISSUE THREAD

**Issue by ctron** [cloudevents/sdk-rust#160]
Assuming you have an event with:

```json
{
  "datacontenttype": "application/json",
  "data_base64": "… non JSON …",
}
```

Then it fails to deserialize the event, as it tries to parse the value as JSON:

https://github.com/cloudevents/sdk-rust/blob/1e89203cbcac1f75e3e5daafacf74eefa907611f/src/event/v10/format.rs#L45

Citing the spec:

> When a CloudEvents is deserialized from JSON, the presence of the `data_base64` member clearly indicates that the value is a Base64 encoded binary data, which the serializer MUST decode into a binary runtime data type.

So parsing this into JSON is OK I guess, but a fallback of Binary must also be possible IMHO if that fails.

**Comment by jcrossley3** [comment]
I'm confused: we have test fixtures that verify proper handling of the `data_base64` binary payload, e.g. https://github.com/cloudevents/sdk-rust/blob/master/src/test/fixtures/v10.rs#L169

Is the fixture wrong? And is `"content_type"` a typo in your example? I would've expected `"datacontenttype"`.

What am I missing?

**Comment by ctron** [comment]
> I'm confused: we have test fixtures that verify proper handling of the `data_base64` binary payload, e.g. https://github.com/cloudevents/sdk-rust/blob/master/src/test/fixtures/v10.rs#L169
> 
> Is the fixture wrong?

No I don't think it is wrong. It is just lacking an additional case.

> And is `"content_type"` a typo in your example? I would've expected `"datacontenttype"`.

Yes, that was wrong. I updated it.

> What am I missing?

What is missing is a test, which has a content type that says "is JSON", but binary data that is not JSON:

I guess the following could work:

~~~rust
pub fn full_json_base64_data_non_json() -> Value {
    let (string_ext_name, string_ext_value) = string_extension();
    let (bool_ext_name, bool_ext_value) = bool_extension();
    let (int_ext_name, int_ext_value) = int_extension();

    json!({
        "specversion": "1.0",
        "id": id(),
        "type": ty(),
        "source": source(),
        "subject": subject(),
        "time": time(),
        string_ext_name: string_ext_value,
        bool_ext_name: bool_ext_value,
        int_ext_name: int_ext_value,
        "datacontenttype": json_datacontenttype(),
        "dataschema": dataschema(),
        "data_base64": base64::encode("hello world".as_bytes())
    })
}
~~~

I also think that not having a content type defaults to "is JSON". If that really is so, then I think the same handling should take place in the case the content type is absent.

**Comment by jcrossley3** [comment]
@ctron mind taking a gander at #161 please?
