### ISSUE TITLE
msgpack serialization

### ISSUE THREAD

**Issue by kesavkolla** [cloudevents/sdk-rust#189]
Hi I am trying to serialize the cloudevent into msgpack. I have the following code:

```rust
use cloudevents::{Event, EventBuilder, EventBuilderV10};
use rmp_serde::{Deserializer, Serializer};
use serde::{Deserialize, Serialize};
use serde_json::json;

let event = EventBuilderV10::new()
      .id("03b0fe1e-1609-645c-203a-2ae014b0febc")
      .ty("company.export")
      .source("webapp")
      .subject("subject")
      .data("application/json", json!({"hello": "world"}))
      .build().unwrap();

let buff = rmp_serde::to_vec_named(&event).unwrap();

let event1 = rmp_serde::from_slice::<Event>(buff.as_slice()).unwrap();
println!("{:?}", event1);

```

When I deserialize the **data** is getting None. I was expecting data should come back what I have set as sample Json.

I am using follwing versions in my cargo.toml:

```toml
serde_json = "1"
rmp-serde = "1"

```

What am I missing from code? Has anyone used msgpack serializattion with cloudevent?

Appreciate some help in identifying the issue.

Thanks in advance

**Comment by jcrossley3** [comment]
Took me a while, but I reproduced the problem. Not sure what's going on, but when I call `.extension(...)` on the builder, the data comes back. Without a call to `.extension`, I lose it. Weird, but I'll figure it out.

**Comment by jcrossley3** [comment]
Thanks for reporting the bug @kesavkolla
