### ISSUE TITLE
remove dev dependency claim

### ISSUE THREAD

**Issue by xiaoas** [cloudevents/sdk-rust#205]
The repo violates version contract, and hasn't received any updates for a long time.
This blocks https://github.com/cloudevents/sdk-rust/issues/204

**Comment by xiaoas** [comment]
```
error: failed to select a version for `autocfg`.
    ... required by package `tokio v1.21.0`
    ... which satisfies dependency `tokio = "^1.21"` of package `axum v0.6.0`
    ... which satisfies dependency `axum-lib = "^0.6"` of package `cloudevents-sdk v0.7.0 (/workspaces/sdk-rust)`
versions that meet the requirements `^1.1` are: 1.1.0

all possible versions conflict with previously selected packages.

  previously selected package `autocfg v1.0.0`
    ... which satisfies dependency `autocfg = "~1.0"` of package `claim v0.3.1`
    ... which satisfies dependency `claim = "^0.3.1"` of package `cloudevents-sdk v0.7.0 (/workspaces/sdk-rust)`

failed to select a version for `autocfg` which could resolve this conflict
```

**Comment by No9** [comment]
FYI I moved to `claims` in this PR https://github.com/cloudevents/sdk-rust/pull/202/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R74 

Let's get some feedback to see which one is preferred.

**Comment by xiaoas** [comment]
I think replacing the dependency with `claims` is a better approach, as it aims to be the direct replacement to `claim`.
whether we need that extra dependency(instead of writing assert_ok! ourselves) can be left to a future discussion.
