### ISSUE TITLE
Kafka (rdkafka) integration

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-rust#54]
Integrate the sdk with [`rdkafka`](https://crates.io/crates/rdkafka), creating a new integration crate `cloudevents-sdk-rdkafka`

**Comment by pranav-bhatt** [comment]
I'm interested in working on this issue

**Comment by slinkydeveloper** [comment]
Done by https://github.com/cloudevents/sdk-rust/pull/60
