### ISSUE TITLE
Marshalling/Unmarshalling of the event data structure to/from JSON

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-rust#6]

**Comment by Lazzaretti** [comment]
this should work with JSON data in different CloudEvents versions

**Comment by slinkydeveloper** [comment]
with data dym the whole event serialized or the payload of the event (`data` field)?

**Comment by Lazzaretti** [comment]
Probably easier with an enum like this: https://github.com/kichristensen/rust-cloudevents/blob/master/cloudevents/src/event.rs
