### ISSUE TITLE
Investigate usage of thiserror to replace snafu

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-rust#70]
At the moment, to generate library errors, we're using snafu. This library is more powerful than we need, we should investigate https://docs.rs/thiserror as alternative, since it provides only the features we really need

**Comment by elpiel** [comment]
If no one is working on this I want to pick it up for hacktoberfest.
I have experience with `thiserror` and it shouldn't be that hard to replace `snafu`

**Comment by slinkydeveloper** [comment]
My only problem with thiserror is that it still does not support `no_std` environments https://github.com/dtolnay/thiserror/pull/64 , which we plan to support at some point #72 . I suggest you to go forward and start replacing snafu with thiserror so we can compare the two, then we'll figure out the no_std thing
