### ISSUE TITLE
no default features for actix-web

### ISSUE THREAD

**Issue by robjtede** [cloudevents/sdk-rust#82]
If/when the actix-web dependency is updated to v3, the dependency in Cargo.toml should ideally be:

```diff
- actix-web = "3.0.2"
+ actix-web = { version = "3.0.2", default-features = false }
```

**Comment by slinkydeveloper** [comment]
Thanks for the report, mind doing a pr?

**Comment by slinkydeveloper** [comment]
Fixed with https://github.com/cloudevents/sdk-rust/pull/85
